### ISSUE TITLE
Does not work if new namespace syntax

### ISSUE THREAD

**Issue by ignatandrei** [YonatanCohavi/DynamicsMapper#1]
If we have 
```csharp
namespace NextGenMapperDemo
{
    [CrmEntity("person")]
    public class Person

```

it generates the files. However , if we write

```csharp
namespace NextGenMapperDemo;
[CrmEntity("person")]
public class Person
{
```
it does not generated

I think that the problems resides here

```charp
var @namespace = mapperSyntax.GetParent<NamespaceDeclarationSyntax>()!.Name.ToString();
var mapperNameSpace = mapperSyntax.GetParent<NamespaceDeclarationSyntax>()!.Name.ToString();
```

I believe that should be BaseNamespaceDeclarationSyntax

https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.csharp.syntax.basenamespacedeclarationsyntax

( I want to add to my list of Roslyn Source Code Generators from https://ignatandrei.github.io/RSCG_Examples/v2/docs/List-of-RSCG )

**Comment by YonatanCohavi** [comment]
thanks for the input. It will be fixed soon.

**Comment by ignatandrei** [comment]
Thanks ! - it is now at https://ignatandrei.github.io/RSCG_Examples/v2/docs/DynamicsMapper
